# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  reverse_cash_refunds:
    class: ReverseCashRefundsJob
    args: []
    schedule: every hour at minute 32

  refresh_affiliate_stats:
    class: RefreshAffiliateStatsJob
    args: []
    schedule: every hour at minute 52

  fund_global_payout_balance_job:
    class: FundGlobalPayoutBalanceJob
    args: []
    schedule: every day at 11pm

  payout_affiliate_rewards_job:
    class: PayoutAffiliateRewardsJob
    args: []
    schedule: every month at 9am
