default: &defaults
  env: <%= Rails.env %>
  bucket: swarm-engine-dev
  scripts_bucket: blendergrid-blender-scripts
  key_prefix: uploads

test:
  <<: *defaults

development:
  <<: *defaults
  env: dev

production:
  <<: *defaults
  env: production
  bucket: blendergrid-production-us-east-1
